### ISSUE TITLE
Issue with songs with "" in their name

### ISSUE THREAD

**Issue by greyhenna** [bunnykek/jiosaavn-dl#2]
Downloading : 160. Koodamela Koodavechi (From "Rummy")...
Traceback (most recent call last):
  File "C:\Users\G\Downloads\jiosaavn-dl-main\jiosaavn.py", line 247, in <module>
    playlist_json_handler(playlist_json, playlist_path)
  File "C:\Users\G\Downloads\jiosaavn-dl-main\jiosaavn.py", line 60, in playlist_json_handler
    download_song(json['songs'].index(
  File "C:\Users\G\Downloads\jiosaavn-dl-main\jiosaavn.py", line 92, in download_song
    with open(song_path, "wb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\G\\Downloads\\jiosaavn-dl-main\\Downloads\\Playlist - sss\\160. Koodamela Koodavechi (From "Rummy").m4a'

I think, As "" is not allowed in filename, script throws the upshown error.

**Comment by bunnykek** [comment]
yeah lol. I have now fixed it.
Do git clone again and `pip install -r requirements.txt`
and then try downloading.

**Comment by greyhenna** [comment]
Thanks for resolving! @bunnykek
