### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chaitrakiran2010** [bunnykek/jiosaavn-dl#6]
here is the error

AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "H:\jiosaavn-dl\jiosaavn.py", line 240, in <module>
    jiosaavn.processAlbum(id_)
  File "H:\jiosaavn-dl\jiosaavn.py", line 94, in processAlbum
    album_json = json.loads(json_rx.search(album_json).group(1))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "H:\jiosaavn-dl\jiosaavn.py", line 240, in <module>
    jiosaavn.processAlbum(id_)
  File "H:\jiosaavn-dl\jiosaavn.py", line 94, in processAlbum
    album_json = json.loads(json_rx.search(album_json).group(1))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by chaitrakiran2010** [comment]
Working....but sometime it shows above error...........
